title: Nathaniel Speiser's blog
description: > # this means to ignore newlines until "baseurl:"
  Nathaniel Speiser's data science blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nathaniel Speiser # add your name
author-img: ns.jpg  # add your photo
about-author: Data scientist, ex-physicist, yak shaver # add description
social-github: nathaniel-speiser # add your Github handle
social-linkedin: nathaniel-speiser # add your Linkedin handle
social-email: nathaniel.speiser@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
